/**
 * Central Error Code Registry
 *
 * Rules:
 * - All codes must follow `DOMAIN_SCREAMING_SNAKE_CASE` naming.
 * - Generic codes (NOT_FOUND, FORBIDDEN, etc.) are FORBIDDEN in service layer.
 *   They may only be used inside middleware as router-level / catch-all fallbacks.
 * - INTERNAL_SERVER_ERROR is assigned automatically by the global error handler
 *   for unknown/non-operational errors.
 * - Object.freeze prevents mutation at runtime.
 */

type DomainPrefix =
    | 'AUTH'
    | 'PAYMENT'
    | 'BOOKING'
    | 'TICKET'
    | 'DIGITAL'
    | 'WHATSAPP'
    | 'TELEGRAM'
    | 'GOOGLE'
    | 'INTEGRATION'
    | 'DATABASE'
    | 'ORDER'
    | 'REFUND'
    | 'CONFIG'
    | 'MAIL'
    | 'VENDOR'
    | 'CATALOG'
    | 'ANALYTICS'
    | 'DELIVERY'
    | 'GEO'
    | 'CONNECTION'
    | 'BILLING'
    | 'EARNINGS'
    | 'COD'
    | 'INTERNAL'      // INTERNAL_SERVER_ERROR
    | 'NOT'           // NOT_FOUND — router-level only
    | 'VALIDATION';   // VALIDATION_ERROR — ZodError catch in global handler only

// Compile-time check: every key must start with a known domain prefix.
// Usage: type Check = ValidCode<'AUTH_INVALID_CREDENTIALS'> // 'AUTH_INVALID_CREDENTIALS'
export type ValidCode<T extends string> = T extends `${DomainPrefix}_${string}` ? T : never;

export const ERROR_CODES = Object.freeze({
    // ── AUTH ──────────────────────────────────────────────────────────────────
    AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
    AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
    AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
    AUTH_MISSING_TOKEN: 'AUTH_MISSING_TOKEN',
    AUTH_ROLE_NOT_FOUND: 'AUTH_ROLE_NOT_FOUND',
    AUTH_ROLE_ALREADY_EXISTS: 'AUTH_ROLE_ALREADY_EXISTS',
    AUTH_ROLE_REQUIRED: 'AUTH_ROLE_REQUIRED',
    AUTH_ACCOUNT_NOT_FOUND: 'AUTH_ACCOUNT_NOT_FOUND',
    AUTH_PHONE_TAKEN: 'AUTH_PHONE_TAKEN',
    AUTH_EMAIL_TAKEN: 'AUTH_EMAIL_TAKEN',
    AUTH_EMAIL_ALREADY_VERIFIED: 'AUTH_EMAIL_ALREADY_VERIFIED',
    AUTH_EMAIL_MISSING: 'AUTH_EMAIL_MISSING',
    AUTH_VERIFY_TOKEN_INVALID: 'AUTH_VERIFY_TOKEN_INVALID',
    AUTH_WA_ALREADY_VERIFIED: 'AUTH_WA_ALREADY_VERIFIED',
    AUTH_PROFILE_NOT_FOUND: 'AUTH_PROFILE_NOT_FOUND',
    AUTH_PHONE_REQUIRED_FOR_WA: 'AUTH_PHONE_REQUIRED_FOR_WA',
    AUTH_UNSUPPORTED_ROLE: 'AUTH_UNSUPPORTED_ROLE',
    AUTH_REFRESH_TOKEN_INVALID: 'AUTH_REFRESH_TOKEN_INVALID',
    AUTH_SESSION_EXPIRED: 'AUTH_SESSION_EXPIRED',
    AUTH_USER_NOT_FOUND: 'AUTH_USER_NOT_FOUND',
    AUTH_ROLE_PROFILE_NOT_FOUND: 'AUTH_ROLE_PROFILE_NOT_FOUND',
    AUTH_WA_PHONE_ID_REQUIRED: 'AUTH_WA_PHONE_ID_REQUIRED',
    AUTH_FORBIDDEN: 'AUTH_FORBIDDEN',

    // ── PAYMENT ───────────────────────────────────────────────────────────────
    PAYMENT_ORDER_NOT_FOUND: 'PAYMENT_ORDER_NOT_FOUND',
    PAYMENT_ORDER_ALREADY_PAID: 'PAYMENT_ORDER_ALREADY_PAID',
    PAYMENT_INVALID_ORDER_STATUS: 'PAYMENT_INVALID_ORDER_STATUS',
    PAYMENT_GATEWAY_NOT_SUPPORTED: 'PAYMENT_GATEWAY_NOT_SUPPORTED',
    PAYMENT_INITIATION_FAILED: 'PAYMENT_INITIATION_FAILED',
    PAYMENT_VERIFICATION_FAILED: 'PAYMENT_VERIFICATION_FAILED',
    PAYMENT_BOOKING_NOT_FOUND: 'PAYMENT_BOOKING_NOT_FOUND',
    PAYMENT_BOOKING_CANCELLED: 'PAYMENT_BOOKING_CANCELLED',
    PAYMENT_BOOKING_NO_PAYMENT_REQUIRED: 'PAYMENT_BOOKING_NO_PAYMENT_REQUIRED',
    PAYMENT_BOOKING_ALREADY_PAID: 'PAYMENT_BOOKING_ALREADY_PAID',
    PAYMENT_BOOKING_IN_PROGRESS: 'PAYMENT_BOOKING_IN_PROGRESS',
    PAYMENT_TRANSACTION_NOT_FOUND: 'PAYMENT_TRANSACTION_NOT_FOUND',
    PAYMENT_WEBHOOK_INVALID_PAYLOAD: 'PAYMENT_WEBHOOK_INVALID_PAYLOAD',
    PAYMENT_MISSING_BOOKING_ID: 'PAYMENT_MISSING_BOOKING_ID',
    PAYMENT_GATEWAY_NOT_IMPLEMENTED: 'PAYMENT_GATEWAY_NOT_IMPLEMENTED',
    PAYMENT_CARD_DECLINED: 'PAYMENT_CARD_DECLINED',
    PAYMENT_CART_NOT_FOUND: 'PAYMENT_CART_NOT_FOUND',
    PAYMENT_CART_NO_PAYABLE_ORDERS: 'PAYMENT_CART_NO_PAYABLE_ORDERS',
    PAYMENT_CART_MIXED_CURRENCY: 'PAYMENT_CART_MIXED_CURRENCY',
    PAYMENT_REFERENCE_REQUIRED: 'PAYMENT_REFERENCE_REQUIRED',
    PAYMENT_ORDER_IS_COD: 'PAYMENT_ORDER_IS_COD',
    STRIPE_WEBHOOK_SIGNATURE_INVALID: 'STRIPE_WEBHOOK_SIGNATURE_INVALID',

    // ── REFUND ────────────────────────────────────────────────────────────────
    REFUND_NOT_ELIGIBLE: 'REFUND_NOT_ELIGIBLE',
    REFUND_WINDOW_EXPIRED: 'REFUND_WINDOW_EXPIRED',
    REFUND_POLICY_DISABLED: 'REFUND_POLICY_DISABLED',
    REFUND_AMOUNT_EXCEEDS_MAX: 'REFUND_AMOUNT_EXCEEDS_MAX',
    REFUND_ALREADY_FULLY_REFUNDED: 'REFUND_ALREADY_FULLY_REFUNDED',
    REFUND_PAYMENT_NOT_FOUND: 'REFUND_PAYMENT_NOT_FOUND',
    REFUND_ORDER_NOT_PAID: 'REFUND_ORDER_NOT_PAID',
    REFUND_GATEWAY_FAILED: 'REFUND_GATEWAY_FAILED',
    REFUND_GATEWAY_NOT_SUPPORTED: 'REFUND_GATEWAY_NOT_SUPPORTED',

    // ── TICKET ────────────────────────────────────────────────────────────────
    TICKET_NOT_FOUND: 'TICKET_NOT_FOUND',
    TICKET_UPDATE_FAILED: 'TICKET_UPDATE_FAILED',
    TICKET_ASSIGN_FAILED: 'TICKET_ASSIGN_FAILED',
    TICKET_PRIORITY_UPDATE_FAILED: 'TICKET_PRIORITY_UPDATE_FAILED',
    TICKET_CLOSE_FAILED: 'TICKET_CLOSE_FAILED',
    TICKET_REOPEN_FAILED: 'TICKET_REOPEN_FAILED',
    TICKET_GENERAL_UPDATE_FAILED: 'TICKET_GENERAL_UPDATE_FAILED',
    TICKET_ACCESS_DENIED: 'TICKET_ACCESS_DENIED',
    TICKET_FOLLOWER_LIMIT_EXCEEDED: 'TICKET_FOLLOWER_LIMIT_EXCEEDED',
    TICKET_ATTACHMENT_LIMIT_EXCEEDED: 'TICKET_ATTACHMENT_LIMIT_EXCEEDED',
    TICKET_ATTACHMENT_MISSING: 'TICKET_ATTACHMENT_MISSING',
    TICKET_PRIORITY_LOCKED: 'TICKET_PRIORITY_LOCKED',
    TICKET_INVALID_STATUS_TRANSITION: 'TICKET_INVALID_STATUS_TRANSITION',
    TICKET_CLOSED: 'TICKET_CLOSED',
    TICKET_WAITING_TARGET_NOT_PARTICIPANT: 'TICKET_WAITING_TARGET_NOT_PARTICIPANT',
    TICKET_CUSTOMER_PRIVATE_NOTE_FORBIDDEN: 'TICKET_CUSTOMER_PRIVATE_NOTE_FORBIDDEN',
    TICKET_REQUIRED_INFO_MISSING: 'TICKET_REQUIRED_INFO_MISSING',
    TICKET_ENTITY_NOT_FOUND: 'TICKET_ENTITY_NOT_FOUND',

    // ── DIGITAL DELIVERY ──────────────────────────────────────────────────────
    DIGITAL_INVALID_ENTITLEMENT_ID: 'DIGITAL_INVALID_ENTITLEMENT_ID',
    DIGITAL_ENTITLEMENT_NOT_FOUND: 'DIGITAL_ENTITLEMENT_NOT_FOUND',
    DIGITAL_ENTITLEMENT_UNAUTHORIZED: 'DIGITAL_ENTITLEMENT_UNAUTHORIZED',
    DIGITAL_ENTITLEMENT_REVOKED: 'DIGITAL_ENTITLEMENT_REVOKED',
    DIGITAL_ENTITLEMENT_EXPIRED: 'DIGITAL_ENTITLEMENT_EXPIRED',
    DIGITAL_ENTITLEMENT_ALREADY_REVOKED: 'DIGITAL_ENTITLEMENT_ALREADY_REVOKED',
    DIGITAL_ENTITLEMENT_NOT_REVOKED: 'DIGITAL_ENTITLEMENT_NOT_REVOKED',
    DIGITAL_DOWNLOAD_LIMIT_EXCEEDED: 'DIGITAL_DOWNLOAD_LIMIT_EXCEEDED',
    DIGITAL_TOKEN_INVALID: 'DIGITAL_TOKEN_INVALID',

    // ── WHATSAPP ──────────────────────────────────────────────────────────────
    WHATSAPP_ROLE_NOT_SUPPORTED: 'WHATSAPP_ROLE_NOT_SUPPORTED',
    WHATSAPP_NOT_LINKED: 'WHATSAPP_NOT_LINKED',

    // ── TELEGRAM ──────────────────────────────────────────────────────────────
    TELEGRAM_NOT_LINKED: 'TELEGRAM_NOT_LINKED',
    TELEGRAM_LINK_FAILED: 'TELEGRAM_LINK_FAILED',
    TELEGRAM_LINK_NOT_FOUND: 'TELEGRAM_LINK_NOT_FOUND',

    // ── GOOGLE / INTEGRATIONS ─────────────────────────────────────────────────
    GOOGLE_MISSING_CLIENT_ID: 'GOOGLE_MISSING_CLIENT_ID',
    GOOGLE_MISSING_CLIENT_SECRET: 'GOOGLE_MISSING_CLIENT_SECRET',
    GOOGLE_MISSING_REDIRECT_URI: 'GOOGLE_MISSING_REDIRECT_URI',
    GOOGLE_PROFILE_FETCH_FAILED: 'GOOGLE_PROFILE_FETCH_FAILED',
    GOOGLE_NO_ACCESS_TOKEN: 'GOOGLE_NO_ACCESS_TOKEN',
    GOOGLE_NO_REFRESH_TOKEN: 'GOOGLE_NO_REFRESH_TOKEN',
    GOOGLE_CALENDAR_NOT_CONNECTED: 'GOOGLE_CALENDAR_NOT_CONNECTED',
    GOOGLE_EVENT_MISSING_ID: 'GOOGLE_EVENT_MISSING_ID',
    GOOGLE_EVENT_MISSING_DATETIME: 'GOOGLE_EVENT_MISSING_DATETIME',
    GOOGLE_TOKEN_ENCRYPTION_KEY_MISSING: 'GOOGLE_TOKEN_ENCRYPTION_KEY_MISSING',
    GOOGLE_TOKEN_INVALID_FORMAT: 'GOOGLE_TOKEN_INVALID_FORMAT',
    INTEGRATION_UNSUPPORTED_CALENDAR_PROVIDER: 'INTEGRATION_UNSUPPORTED_CALENDAR_PROVIDER',

    // ── DATABASE ──────────────────────────────────────────────────────────────
    DATABASE_UNAVAILABLE: 'DATABASE_UNAVAILABLE',
    DATABASE_CONNECTION_ERROR: 'DATABASE_CONNECTION_ERROR',
    DATABASE_UNIQUE_CONSTRAINT_VIOLATION: 'DATABASE_UNIQUE_CONSTRAINT_VIOLATION',

    // ── ORDER ─────────────────────────────────────────────────────────────────
    ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',
    ORDER_PAYMENT_FAILED: 'ORDER_PAYMENT_FAILED',
    ORDER_TERMINAL_STATE: 'ORDER_TERMINAL_STATE',
    ORDER_INVALID_TRANSITION: 'ORDER_INVALID_TRANSITION',
    ORDER_PAYMENT_REQUIRED: 'ORDER_PAYMENT_REQUIRED',
    ORDER_PAYMENT_FAILED_STATE: 'ORDER_PAYMENT_FAILED_STATE',
    ORDER_DISPUTE_HOLD: 'ORDER_DISPUTE_HOLD',
    ORDER_WRONG_TYPE: 'ORDER_WRONG_TYPE',
    ORDER_DELIVERY_AGENCY_NOT_FOUND: 'ORDER_DELIVERY_AGENCY_NOT_FOUND',
    ORDER_ITEM_NOT_FOUND: 'ORDER_ITEM_NOT_FOUND',
    ORDER_ITEM_NOT_REASSIGNABLE: 'ORDER_ITEM_NOT_REASSIGNABLE',
    SHIPMENT_NOT_FOUND: 'SHIPMENT_NOT_FOUND',
    SHIPMENT_INVALID_STATUS_TRANSITION: 'SHIPMENT_INVALID_STATUS_TRANSITION',
    SHIPMENT_REJECTION_NOT_ALLOWED: 'SHIPMENT_REJECTION_NOT_ALLOWED',
    SHIPMENT_AGENT_NOT_IN_AGENCY: 'SHIPMENT_AGENT_NOT_IN_AGENCY',
    SHIPMENT_ACCESS_DENIED: 'SHIPMENT_ACCESS_DENIED',
    SHIPMENT_ALREADY_CONFIRMED: 'SHIPMENT_ALREADY_CONFIRMED',
    SHIPMENT_CONFIRMATION_NOT_ALLOWED: 'SHIPMENT_CONFIRMATION_NOT_ALLOWED',
    // The auto-generated tracking number collided on every attempt — see
    // TrackingNumberGenerator. Effectively unreachable; it means a broken clock
    // or RNG rather than bad luck.
    SHIPMENT_TRACKING_NUMBER_GENERATION_FAILED: 'SHIPMENT_TRACKING_NUMBER_GENERATION_FAILED',
    // Agent-acceptance workflow (shipment assignment offers)
    SHIPMENT_OFFER_NOT_FOUND: 'SHIPMENT_OFFER_NOT_FOUND',
    SHIPMENT_OFFER_NOT_PENDING: 'SHIPMENT_OFFER_NOT_PENDING',
    SHIPMENT_OFFER_EXPIRED: 'SHIPMENT_OFFER_EXPIRED',
    SHIPMENT_NOT_OFFERABLE: 'SHIPMENT_NOT_OFFERABLE',
    SHIPMENT_ALREADY_HAS_AGENT: 'SHIPMENT_ALREADY_HAS_AGENT',
    SHIPMENT_ALREADY_HAS_PENDING_OFFER: 'SHIPMENT_ALREADY_HAS_PENDING_OFFER',
    SHIPMENT_NO_ELIGIBLE_AGENTS: 'SHIPMENT_NO_ELIGIBLE_AGENTS',
    // No agent has accepted the shipment yet — it cannot be picked up.
    SHIPMENT_AGENT_NOT_ASSIGNED: 'SHIPMENT_AGENT_NOT_ASSIGNED',
    // Agent → agent reassignment (moving a shipment off its current agent).
    SHIPMENT_NOT_REASSIGNABLE: 'SHIPMENT_NOT_REASSIGNABLE',
    SHIPMENT_REASSIGNMENT_NOT_ALLOWED: 'SHIPMENT_REASSIGNMENT_NOT_ALLOWED',
    SHIPMENT_REASSIGN_SAME_AGENT: 'SHIPMENT_REASSIGN_SAME_AGENT',
    SHIPMENT_REASSIGN_REQUIRES_MANUAL_AGENT: 'SHIPMENT_REASSIGN_REQUIRES_MANUAL_AGENT',
    SHIPMENT_REASSIGNMENT_CONFLICT: 'SHIPMENT_REASSIGNMENT_CONFLICT',
    // Agent-initiated mid-delivery cancellation (releases the agent, resumes auto-assignment).
    SHIPMENT_CANCEL_NOT_ALLOWED: 'SHIPMENT_CANCEL_NOT_ALLOWED',
    SHIPMENT_CANCEL_CONFLICT: 'SHIPMENT_CANCEL_CONFLICT',
    // The shipment moved between the read that validated the transition and the
    // write — the other actor (agency vs agent, who now drive the same state
    // machine) got there first. Retry from a fresh read.
    SHIPMENT_STATUS_CONFLICT: 'SHIPMENT_STATUS_CONFLICT',
    // Agent delivery-proof upload allowed only at/after the delivery outcome.
    SHIPMENT_PROOF_NOT_ALLOWED: 'SHIPMENT_PROOF_NOT_ALLOWED',
    SHIPMENT_PROOF_NOT_FOUND: 'SHIPMENT_PROOF_NOT_FOUND',
    SHIPMENT_PROOF_FILE_REQUIRED: 'SHIPMENT_PROOF_FILE_REQUIRED',
    ORDER_ALREADY_CANCELLED: 'ORDER_ALREADY_CANCELLED',
    ORDER_NOT_CANCELLABLE: 'ORDER_NOT_CANCELLABLE',
    ORDER_CANCEL_REQUIRES_REFUND: 'ORDER_CANCEL_REQUIRES_REFUND',
    // Shared by order + booking customer cancellation (vendor cancellation_policy gate).
    CANCELLATION_NOT_ALLOWED: 'CANCELLATION_NOT_ALLOWED',

    // ── CONFIG / INFRA ────────────────────────────────────────────────────────
    CONFIG_MISSING_WA_ACCESS_TOKEN: 'CONFIG_MISSING_WA_ACCESS_TOKEN',
    CONFIG_MISSING_WA_PHONE_ID: 'CONFIG_MISSING_WA_PHONE_ID',
    CONFIG_MISSING_STORAGE_PROVIDER: 'CONFIG_MISSING_STORAGE_PROVIDER',
    CONFIG_NOTIFICATION_CATALOG_INCOMPLETE: 'CONFIG_NOTIFICATION_CATALOG_INCOMPLETE',
    CONFIG_INVALID_STORAGE_PROVIDER: 'CONFIG_INVALID_STORAGE_PROVIDER',
    CONFIG_INVALID_GEO_PROVIDER: 'CONFIG_INVALID_GEO_PROVIDER',
    STORAGE_UPLOAD_FAILED: 'STORAGE_UPLOAD_FAILED',
    UPLOAD_POLICY_VIOLATION: 'UPLOAD_POLICY_VIOLATION',

    // ── GEO / GEOCODING (address search & reverse geocoding) ──────────────────
    // Provider selected but its adapter/credentials are missing in this build.
    GEO_PROVIDER_NOT_CONFIGURED: 'GEO_PROVIDER_NOT_CONFIGURED',
    // Provider unreachable — network failure or timeout (fail soft; geo is off
    // the critical path, so deliveries/checkout keep working).
    GEO_PROVIDER_UNAVAILABLE: 'GEO_PROVIDER_UNAVAILABLE',
    // Provider returned a non-2xx or unparseable response.
    GEO_SEARCH_FAILED: 'GEO_SEARCH_FAILED',
    // A new/edited business or headquarters address was submitted without a
    // geocoded `geo` (a selected /api/geo/search result). Required so every
    // physical location is mappable and its country verifiable.
    ADDRESS_GEO_REQUIRED: 'ADDRESS_GEO_REQUIRED',
    // A geocoded address resolves outside the profile's registered country
    // (or its provider returned no country code, so it cannot be verified).
    ADDRESS_COUNTRY_MISMATCH: 'ADDRESS_COUNTRY_MISMATCH',
    // Attempt to change a profile country that is already set. Country is
    // chosen during onboarding and immutable afterwards (tax/shipping policy).
    PROFILE_COUNTRY_IMMUTABLE: 'PROFILE_COUNTRY_IMMUTABLE',

    // ── MAIL ──────────────────────────────────────────────────────────────────
    MAIL_TEMPLATE_NOT_FOUND: 'MAIL_TEMPLATE_NOT_FOUND',

    // ── VENDORS ─────────────────────────────────────────────────────────────
    VENDOR_UNSUPPORTED_FISCAL_CALENDAR: 'VENDOR_UNSUPPORTED_FISCAL_CALENDAR',

    // ── CATALOG / INVENTORY (EXPANDED) ────────────────────────────────────────
    CATALOG_INSUFFICIENT_STOCK: 'CATALOG_INSUFFICIENT_STOCK',
    CATALOG_OVERSALE_NOT_ALLOWED: 'CATALOG_OVERSALE_NOT_ALLOWED',
    CATALOG_INVALID_CSV_FORMAT: 'CATALOG_INVALID_CSV_FORMAT',
    CATALOG_BULK_VALIDATION_FAILED: 'CATALOG_BULK_VALIDATION_FAILED',
    CATALOG_RESERVATION_EXPIRED: 'CATALOG_RESERVATION_EXPIRED',
    CATALOG_TRANSACTION_LIMIT_EXCEEDED: 'CATALOG_TRANSACTION_LIMIT_EXCEEDED',
    // Products
    CATALOG_PRODUCT_NOT_FOUND: 'CATALOG_PRODUCT_NOT_FOUND',
    CATALOG_PRODUCT_ACCESS_DENIED: 'CATALOG_PRODUCT_ACCESS_DENIED',
    CATALOG_PRODUCT_INVALID_STATE: 'CATALOG_PRODUCT_INVALID_STATE',
    CATALOG_PRODUCT_INVALID_TITLE: 'CATALOG_PRODUCT_INVALID_TITLE',
    CATALOG_PRODUCT_NO_DESCRIPTION: 'CATALOG_PRODUCT_NO_DESCRIPTION',
    CATALOG_PRODUCT_ALREADY_PUBLISHED: 'CATALOG_PRODUCT_ALREADY_PUBLISHED',
    CATALOG_PRODUCT_NO_VARIANTS: 'CATALOG_PRODUCT_NO_VARIANTS',
    CATALOG_PRODUCT_NO_DEFAULT_VARIANT: 'CATALOG_PRODUCT_NO_DEFAULT_VARIANT',
    CATALOG_PRODUCT_DIGITAL_NO_ASSET: 'CATALOG_PRODUCT_DIGITAL_NO_ASSET',
    CATALOG_PRODUCT_SERVICE_NO_DURATION: 'CATALOG_PRODUCT_SERVICE_NO_DURATION',
    CATALOG_PRODUCT_SERVICE_NO_CAPACITY: 'CATALOG_PRODUCT_SERVICE_NO_CAPACITY',
    CATALOG_PRODUCT_SERVICE_NO_AVAILABILITY: 'CATALOG_PRODUCT_SERVICE_NO_AVAILABILITY',
    CATALOG_PRODUCT_VARIANT_ZERO_PRICE: 'CATALOG_PRODUCT_VARIANT_ZERO_PRICE',
    CATALOG_PRODUCT_NOT_DIGITAL: 'CATALOG_PRODUCT_NOT_DIGITAL',
    CATALOG_PRODUCT_NO_DIGITAL_CONFIG: 'CATALOG_PRODUCT_NO_DIGITAL_CONFIG',
    CATALOG_PRODUCT_NO_DELIVERY_AGENCY: 'CATALOG_PRODUCT_NO_DELIVERY_AGENCY',
    CATALOG_PRODUCT_NO_PICKUP_LOCATION: 'CATALOG_PRODUCT_NO_PICKUP_LOCATION',
    CATALOG_PRODUCT_INVALID_PICKUP_LOCATION: 'CATALOG_PRODUCT_INVALID_PICKUP_LOCATION',
    CATALOG_PRODUCT_VECTORISATION_PENDING: 'CATALOG_PRODUCT_VECTORISATION_PENDING',
    CATALOG_PRODUCT_VECTORISATION_NOT_ELIGIBLE: 'CATALOG_PRODUCT_VECTORISATION_NOT_ELIGIBLE',
    // Authoring mode (see product.model.ts ProductMode). A `simple` product is
    // locked to exactly one variant and zero options; the advanced endpoints
    // refuse it, and the simple endpoints refuse an advanced product.
    CATALOG_PRODUCT_SIMPLE_MODE_LOCKED: 'CATALOG_PRODUCT_SIMPLE_MODE_LOCKED',
    CATALOG_PRODUCT_NOT_SIMPLE_MODE: 'CATALOG_PRODUCT_NOT_SIMPLE_MODE',
    // Variants
    CATALOG_VARIANT_NOT_FOUND: 'CATALOG_VARIANT_NOT_FOUND',
    CATALOG_VARIANT_ACCESS_DENIED: 'CATALOG_VARIANT_ACCESS_DENIED',
    CATALOG_VARIANT_ARCHIVED: 'CATALOG_VARIANT_ARCHIVED',
    CATALOG_VARIANT_INVALID_STOCK: 'CATALOG_VARIANT_INVALID_STOCK',
    CATALOG_VARIANT_INVALID_PRICE: 'CATALOG_VARIANT_INVALID_PRICE',
    CATALOG_VARIANT_COMPARE_PRICE_INVALID: 'CATALOG_VARIANT_COMPARE_PRICE_INVALID',
    CATALOG_VARIANT_LIMIT_EXCEEDED: 'CATALOG_VARIANT_LIMIT_EXCEEDED',
    CATALOG_VARIANT_NO_OPTIONS: 'CATALOG_VARIANT_NO_OPTIONS',
    CATALOG_VARIANT_OPTION_EMPTY: 'CATALOG_VARIANT_OPTION_EMPTY',
    CATALOG_VARIANT_INSUFFICIENT_STOCK: 'CATALOG_VARIANT_INSUFFICIENT_STOCK',
    CATALOG_VARIANT_UNSUPPORTED_TYPE: 'CATALOG_VARIANT_UNSUPPORTED_TYPE',
    CATALOG_VARIANT_NO_DIGITAL_ASSET: 'CATALOG_VARIANT_NO_DIGITAL_ASSET',
    CATALOG_DIGITAL_VARIANT_LIMIT_EXCEEDED: 'CATALOG_DIGITAL_VARIANT_LIMIT_EXCEEDED',
    // Service products carry config + price on a single variant — at most one allowed.
    CATALOG_SERVICE_VARIANT_EXISTS: 'CATALOG_SERVICE_VARIANT_EXISTS',
    CATALOG_VARIANT_INVALID_QUANTITY: 'CATALOG_VARIANT_INVALID_QUANTITY',
    CATALOG_VARIANT_STOCK_ONLY_PHYSICAL: 'CATALOG_VARIANT_STOCK_ONLY_PHYSICAL',
    CATALOG_VARIANT_RESERVATION_CONFLICT: 'CATALOG_VARIANT_RESERVATION_CONFLICT',
    // Options
    CATALOG_OPTION_NOT_FOUND: 'CATALOG_OPTION_NOT_FOUND',
    CATALOG_OPTION_ACCESS_DENIED: 'CATALOG_OPTION_ACCESS_DENIED',
    CATALOG_OPTION_LIMIT_EXCEEDED: 'CATALOG_OPTION_LIMIT_EXCEEDED',
    CATALOG_OPTION_DUPLICATE_NAME: 'CATALOG_OPTION_DUPLICATE_NAME',
    CATALOG_OPTION_REQUIRES_VALUES: 'CATALOG_OPTION_REQUIRES_VALUES',
    CATALOG_OPTION_DUPLICATE_VALUE: 'CATALOG_OPTION_DUPLICATE_VALUE',
    CATALOG_OPTION_VALUES_EXIST: 'CATALOG_OPTION_VALUES_EXIST',
    CATALOG_OPTION_REQUIRES_NO_OPTIONS: 'CATALOG_OPTION_REQUIRES_NO_OPTIONS',
    CATALOG_PRODUCT_INVALID_TYPE: 'CATALOG_PRODUCT_INVALID_TYPE',
    CATALOG_VARIANT_SKU_EXISTS: 'CATALOG_VARIANT_SKU_EXISTS',
    CATALOG_INVALID_OPTION_ID: 'CATALOG_INVALID_OPTION_ID',
    CATALOG_INVALID_CSV: 'CATALOG_INVALID_CSV',
    CATALOG_DIGITAL_ASSET_ALREADY_EXISTS: 'CATALOG_DIGITAL_ASSET_ALREADY_EXISTS',
    CATALOG_DIGITAL_ASSET_MISSING: 'CATALOG_DIGITAL_ASSET_MISSING',
    CATALOG_DIGITAL_CONFIG_MISSING: 'CATALOG_DIGITAL_CONFIG_MISSING',
    CATALOG_FILE_TOO_LARGE: 'CATALOG_FILE_TOO_LARGE',
    CATALOG_FILE_TYPE_INVALID: 'CATALOG_FILE_TYPE_INVALID',
    CATALOG_DIGITAL_ASSET_MISSING_FILE: 'CATALOG_DIGITAL_ASSET_MISSING_FILE',
    // Digital assets
    CATALOG_DIGITAL_ASSET_NOT_FOUND: 'CATALOG_DIGITAL_ASSET_NOT_FOUND',
    CATALOG_VARIANT_RESERVATION_NOT_FOUND: 'CATALOG_VARIANT_RESERVATION_NOT_FOUND',
    // File / media
    CATALOG_FILE_NOT_FOUND: 'CATALOG_FILE_NOT_FOUND',
    CATALOG_FILE_ALREADY_ATTACHED: 'CATALOG_FILE_ALREADY_ATTACHED',
    CATALOG_FILE_STILL_REFERENCED: 'CATALOG_FILE_STILL_REFERENCED',
    CATALOG_IMAGE_LIMIT_EXCEEDED: 'CATALOG_IMAGE_LIMIT_EXCEEDED',
    // Booking / service
    CATALOG_BOOKING_PRODUCT_NOT_FOUND: 'CATALOG_BOOKING_PRODUCT_NOT_FOUND',
    CATALOG_BOOKING_INVALID_PRODUCT_TYPE: 'CATALOG_BOOKING_INVALID_PRODUCT_TYPE',
    CATALOG_BOOKING_MISSING_SERVICE_CONFIG: 'CATALOG_BOOKING_MISSING_SERVICE_CONFIG',
    CATALOG_BOOKING_PRODUCT_NOT_ACTIVE: 'CATALOG_BOOKING_PRODUCT_NOT_ACTIVE',
    CATALOG_BOOKING_INVALID_PRICE: 'CATALOG_BOOKING_INVALID_PRICE',
    CATALOG_BOOKING_NOT_IMPLEMENTED: 'CATALOG_BOOKING_NOT_IMPLEMENTED',
    // Bulk stock
    CATALOG_BULK_LIMIT_EXCEEDED: 'CATALOG_BULK_LIMIT_EXCEEDED',
    CATALOG_BULK_EMPTY: 'CATALOG_BULK_EMPTY',
    CATALOG_BULK_TRANSACTION_LIMIT: 'CATALOG_BULK_TRANSACTION_LIMIT',
    CATALOG_BULK_UPDATE_FAILED: 'CATALOG_BULK_UPDATE_FAILED',

    // ── ANALYTICS ────────────────────────────────────────────────────────────
    ANALYTICS_INVALID_DATE_RANGE: 'ANALYTICS_INVALID_DATE_RANGE',
    ANALYTICS_UNSUPPORTED_TIMEZONE: 'ANALYTICS_UNSUPPORTED_TIMEZONE',
    ANALYTICS_AGGREGATION_NOT_READY: 'ANALYTICS_AGGREGATION_NOT_READY',
    ANALYTICS_DATE_RANGE_EXCEEDED: 'ANALYTICS_DATE_RANGE_EXCEEDED',

    // ── DELIVERY ──────────────────────────────────────────────────────────────
    DELIVERY_AGENCY_NOT_FOUND: 'DELIVERY_AGENCY_NOT_FOUND',
    AGENCY_COVERAGE_AREA_INVALID: 'AGENCY_COVERAGE_AREA_INVALID',
    DELIVERY_AGENT_NOT_FOUND: 'DELIVERY_AGENT_NOT_FOUND',
    DELIVERY_AGENCY_ALREADY_EXISTS: 'DELIVERY_AGENCY_ALREADY_EXISTS',
    DELIVERY_ONBOARDING_STEP_INVALID: 'DELIVERY_ONBOARDING_STEP_INVALID',
    DELIVERY_ONBOARDING_STEP_INCOMPLETE: 'DELIVERY_ONBOARDING_STEP_INCOMPLETE',
    DELIVERY_ONBOARDING_ALREADY_COMPLETED: 'DELIVERY_ONBOARDING_ALREADY_COMPLETED',
    DELIVERY_ONBOARDING_CONCURRENT_MODIFICATION: 'DELIVERY_ONBOARDING_CONCURRENT_MODIFICATION',
    DELIVERY_POLICY_DOCUMENT_MISSING: 'DELIVERY_POLICY_DOCUMENT_MISSING',
    DELIVERY_POLICY_DOCUMENT_TYPE_INVALID: 'DELIVERY_POLICY_DOCUMENT_TYPE_INVALID',
    DELIVERY_AGENT_ALREADY_IN_AGENCY: 'DELIVERY_AGENT_ALREADY_IN_AGENCY',
    DELIVERY_AGENT_NOT_IN_AGENCY: 'DELIVERY_AGENT_NOT_IN_AGENCY',
    DELIVERY_AGENT_HAS_ACTIVE_SHIPMENTS: 'DELIVERY_AGENT_HAS_ACTIVE_SHIPMENTS',
    DELIVERY_AGENCY_NOTIFICATION_NOT_FOUND: 'DELIVERY_AGENCY_NOTIFICATION_NOT_FOUND',
    DELIVERY_AGENCY_NOTIFICATION_CHANNEL_NOT_VERIFIED: 'DELIVERY_AGENCY_NOTIFICATION_CHANNEL_NOT_VERIFIED',
    DELIVERY_AGENCY_NOTIFICATION_DELIVERY_FAILED: 'DELIVERY_AGENCY_NOTIFICATION_DELIVERY_FAILED',
    DELIVERY_AGENT_NOTIFICATION_NOT_FOUND: 'DELIVERY_AGENT_NOTIFICATION_NOT_FOUND',
    DELIVERY_AGENT_NOTIFICATION_CHANNEL_NOT_VERIFIED: 'DELIVERY_AGENT_NOTIFICATION_CHANNEL_NOT_VERIFIED',
    DELIVERY_AGENT_NOTIFICATION_DELIVERY_FAILED: 'DELIVERY_AGENT_NOTIFICATION_DELIVERY_FAILED',

    // ── AGENT (the agent domain: profile, membership, availability, tracking) ──
    AGENT_NOT_FOUND: 'AGENT_NOT_FOUND',
    AGENT_NOT_ACTIVE: 'AGENT_NOT_ACTIVE',
    AGENT_SUSPENDED: 'AGENT_SUSPENDED',
    // Onboarding (locks once completed — edits then go through profile/settings)
    AGENT_ONBOARDING_ALREADY_COMPLETED: 'AGENT_ONBOARDING_ALREADY_COMPLETED',
    // Membership lifecycle
    AGENT_MEMBERSHIP_NOT_FOUND: 'AGENT_MEMBERSHIP_NOT_FOUND',
    AGENT_MEMBERSHIP_ALREADY_EXISTS: 'AGENT_MEMBERSHIP_ALREADY_EXISTS',
    AGENT_MEMBERSHIP_NOT_PENDING: 'AGENT_MEMBERSHIP_NOT_PENDING',
    AGENT_MEMBERSHIP_NOT_APPROVED: 'AGENT_MEMBERSHIP_NOT_APPROVED',
    AGENT_MEMBERSHIP_ALREADY_APPROVED: 'AGENT_MEMBERSHIP_ALREADY_APPROVED',
    AGENT_MEMBERSHIP_SUSPENDED: 'AGENT_MEMBERSHIP_SUSPENDED',
    AGENT_MEMBERSHIP_NOT_SUSPENDED: 'AGENT_MEMBERSHIP_NOT_SUSPENDED',
    AGENT_MEMBERSHIP_INVALID_TRANSITION: 'AGENT_MEMBERSHIP_INVALID_TRANSITION',
    AGENT_MEMBERSHIP_LIMIT_REACHED: 'AGENT_MEMBERSHIP_LIMIT_REACHED',
    AGENT_MEMBERSHIP_HAS_ACTIVE_SHIPMENTS: 'AGENT_MEMBERSHIP_HAS_ACTIVE_SHIPMENTS',
    AGENT_TRANSFER_SAME_AGENCY: 'AGENT_TRANSFER_SAME_AGENCY',
    // Availability / working state
    AGENT_AVAILABILITY_INVALID_TRANSITION: 'AGENT_AVAILABILITY_INVALID_TRANSITION',
    AGENT_AT_CAPACITY: 'AGENT_AT_CAPACITY',
    // Tracking (business flag — geo-tracker enforces, wimall owns)
    AGENT_TRACKING_NOT_ALLOWED: 'AGENT_TRACKING_NOT_ALLOWED',
    AGENT_DEVICE_LOCATION_DISABLED: 'AGENT_DEVICE_LOCATION_DISABLED',
    AGENT_DEVICE_STATE_UNKNOWN: 'AGENT_DEVICE_STATE_UNKNOWN',
    // Assignment eligibility (aggregate — details carry the failed rules)
    AGENT_NOT_ELIGIBLE_FOR_ASSIGNMENT: 'AGENT_NOT_ELIGIBLE_FOR_ASSIGNMENT',
    // COD threshold allocation (agent global pool ← contract sub-allocations)
    AGENT_COD_THRESHOLD_OUT_OF_BOUNDS: 'AGENT_COD_THRESHOLD_OUT_OF_BOUNDS',
    AGENT_COD_THRESHOLD_BELOW_ALLOCATED: 'AGENT_COD_THRESHOLD_BELOW_ALLOCATED',
    CONTRACT_COD_THRESHOLD_OUT_OF_BOUNDS: 'CONTRACT_COD_THRESHOLD_OUT_OF_BOUNDS',
    CONTRACT_COD_THRESHOLD_EXCEEDS_HEADROOM: 'CONTRACT_COD_THRESHOLD_EXCEEDS_HEADROOM',
    CONTRACT_COD_THRESHOLD_BELOW_OUTSTANDING: 'CONTRACT_COD_THRESHOLD_BELOW_OUTSTANDING',
    // Capacity
    AGENT_CAPACITY_OUT_OF_BOUNDS: 'AGENT_CAPACITY_OUT_OF_BOUNDS',
    AGENT_CAPACITY_BELOW_IN_USE: 'AGENT_CAPACITY_BELOW_IN_USE',
    // Contract lifecycle
    CONTRACT_NOT_FOUND: 'CONTRACT_NOT_FOUND',
    CONTRACT_INVALID_TRANSITION: 'CONTRACT_INVALID_TRANSITION',
    CONTRACT_HAS_OUTSTANDING_COD: 'CONTRACT_HAS_OUTSTANDING_COD',
    CONTRACT_HAS_UNPAID_EARNINGS: 'CONTRACT_HAS_UNPAID_EARNINGS',
    CONTRACT_TRANSITION_NOT_PERMITTED: 'CONTRACT_TRANSITION_NOT_PERMITTED',
    // Status-change request workflow
    CONTRACT_STATUS_REQUEST_NOT_FOUND: 'CONTRACT_STATUS_REQUEST_NOT_FOUND',
    CONTRACT_STATUS_REQUEST_NOT_PENDING: 'CONTRACT_STATUS_REQUEST_NOT_PENDING',
    CONTRACT_STATUS_REQUEST_ALREADY_PENDING: 'CONTRACT_STATUS_REQUEST_ALREADY_PENDING',
    CONTRACT_STATUS_REQUEST_NOT_YOURS: 'CONTRACT_STATUS_REQUEST_NOT_YOURS',
    // Coverage / contract terms
    CONTRACT_COVERAGE_OUTSIDE_AGENT_RADIUS: 'CONTRACT_COVERAGE_OUTSIDE_AGENT_RADIUS',
    CONTRACT_COVERAGE_REGION_NOT_COVERED: 'CONTRACT_COVERAGE_REGION_NOT_COVERED',
    CONTRACT_SHIPMENT_VALUE_EXCEEDED: 'CONTRACT_SHIPMENT_VALUE_EXCEEDED',
    CONTRACT_FEE_SPLIT_INVALID: 'CONTRACT_FEE_SPLIT_INVALID',
    // Terms negotiation. CONTRACT_TERMS_NOT_PROPOSED is the guard that makes a
    // bare join-request work: terms nobody stated cannot be approved.
    CONTRACT_TERMS_REQUIRED: 'CONTRACT_TERMS_REQUIRED',
    CONTRACT_TERMS_NOT_PROPOSED: 'CONTRACT_TERMS_NOT_PROPOSED',
    CONTRACT_TERMS_NOT_NEGOTIABLE: 'CONTRACT_TERMS_NOT_NEGOTIABLE',
    CONTRACT_TERMS_LIVE_EDIT_NOT_ALLOWED: 'CONTRACT_TERMS_LIVE_EDIT_NOT_ALLOWED',
    CONTRACT_TERMS_PROPOSAL_NOT_FOUND: 'CONTRACT_TERMS_PROPOSAL_NOT_FOUND',
    CONTRACT_TERMS_PROPOSAL_NOT_PENDING: 'CONTRACT_TERMS_PROPOSAL_NOT_PENDING',
    CONTRACT_TERMS_PROPOSAL_ALREADY_PENDING: 'CONTRACT_TERMS_PROPOSAL_ALREADY_PENDING',
    CONTRACT_TERMS_PROPOSAL_NOT_YOURS: 'CONTRACT_TERMS_PROPOSAL_NOT_YOURS',
    // Settlement (COD remittance under a contract). Thrown by AgentDepositService,
    // which owns the settlement path; there is no separate settlement collection.
    CONTRACT_SETTLEMENT_EXCEEDS_OUTSTANDING: 'CONTRACT_SETTLEMENT_EXCEEDS_OUTSTANDING',
    // Platform gates (run BEFORE COD/capacity)
    AGENT_KYC_NOT_VERIFIED: 'AGENT_KYC_NOT_VERIFIED',
    AGENT_PLATFORM_BANNED: 'AGENT_PLATFORM_BANNED',
    AGENT_PAYOUT_DETAILS_MISSING: 'AGENT_PAYOUT_DETAILS_MISSING',
    // Service-to-service auth (geo-tracker → wimall)
    AGENT_SERVICE_TOKEN_INVALID: 'AGENT_SERVICE_TOKEN_INVALID',
    AGENT_SERVICE_TOKEN_NOT_CONFIGURED: 'AGENT_SERVICE_TOKEN_NOT_CONFIGURED',

    // ── CONNECTION (vendor <-> agency consensual linking) ─────────────────────
    CONNECTION_NOT_FOUND: 'CONNECTION_NOT_FOUND',
    CONNECTION_VENDOR_NOT_FOUND: 'CONNECTION_VENDOR_NOT_FOUND',
    CONNECTION_ALREADY_EXISTS: 'CONNECTION_ALREADY_EXISTS',
    CONNECTION_INVALID_STATUS_TRANSITION: 'CONNECTION_INVALID_STATUS_TRANSITION',
    CONNECTION_NOT_PENDING: 'CONNECTION_NOT_PENDING',
    CONNECTION_NOT_PAUSED: 'CONNECTION_NOT_PAUSED',
    CONNECTION_NOT_REQUESTER: 'CONNECTION_NOT_REQUESTER',
    CONNECTION_NOT_APPROVER: 'CONNECTION_NOT_APPROVER',
    CONNECTION_WRONG_REAPPROVAL_PARTY: 'CONNECTION_WRONG_REAPPROVAL_PARTY',
    CONNECTION_NOT_ACTIVE: 'CONNECTION_NOT_ACTIVE',

    // ── CUSTOMER ──────────────────────────────────────────────────────────────
    CUSTOMER_NOT_FOUND: 'CUSTOMER_NOT_FOUND',
    CUSTOMER_ADDRESS_NOT_FOUND: 'CUSTOMER_ADDRESS_NOT_FOUND',
    CUSTOMER_PAYMENT_METHOD_NOT_FOUND: 'CUSTOMER_PAYMENT_METHOD_NOT_FOUND',

    // ── PAYMENT METHODS (per-user saved instruments) ──────────────────────────
    PAYMENT_METHOD_NOT_FOUND: 'PAYMENT_METHOD_NOT_FOUND',
    PAYMENT_METHOD_LIMIT_REACHED: 'PAYMENT_METHOD_LIMIT_REACHED',

    // ── USER ──────────────────────────────────────────────────────────────────
    USER_NOT_FOUND: 'USER_NOT_FOUND',
    USER_INVALID_PASSWORD: 'USER_INVALID_PASSWORD',

    // ── STORE ─────────────────────────────────────────────────────────────────
    STORE_NOT_FOUND: 'STORE_NOT_FOUND',
    STORE_SLUG_TAKEN: 'STORE_SLUG_TAKEN',

    // ── MAGAZIN (agency business surface) ───────────────────────────────────────
    MAGAZIN_NOT_FOUND: 'MAGAZIN_NOT_FOUND',
    MAGAZIN_CONFLICT: 'MAGAZIN_CONFLICT',

    // ── VENDOR ────────────────────────────────────────────────────────────────
    VENDOR_FISCAL_CALENDAR_INVALID: 'VENDOR_FISCAL_CALENDAR_INVALID',
    VENDOR_BUSINESS_ADDRESS_IN_USE: 'VENDOR_BUSINESS_ADDRESS_IN_USE',
    VENDOR_NOTIFICATION_NOT_FOUND: 'VENDOR_NOTIFICATION_NOT_FOUND',
    VENDOR_NOTIFICATION_CHANNEL_NOT_VERIFIED: 'VENDOR_NOTIFICATION_CHANNEL_NOT_VERIFIED',
    VENDOR_NOTIFICATION_DELIVERY_FAILED: 'VENDOR_NOTIFICATION_DELIVERY_FAILED',
    VENDOR_ONBOARDING_CONCURRENT_MODIFICATION: 'VENDOR_ONBOARDING_CONCURRENT_MODIFICATION',
    VENDOR_ONBOARDING_STEP_INCOMPLETE: 'VENDOR_ONBOARDING_STEP_INCOMPLETE',
    VENDOR_ONBOARDING_STEP_INVALID: 'VENDOR_ONBOARDING_STEP_INVALID',
    VENDOR_ONBOARDING_ALREADY_COMPLETED: 'VENDOR_ONBOARDING_ALREADY_COMPLETED',
    VENDOR_CUSTOMER_NOT_FOUND: 'VENDOR_CUSTOMER_NOT_FOUND',
    VENDOR_CUSTOMER_FLAG_NOT_FOUND: 'VENDOR_CUSTOMER_FLAG_NOT_FOUND',
    VENDOR_CUSTOMER_FLAG_DUPLICATE: 'VENDOR_CUSTOMER_FLAG_DUPLICATE',
    VENDOR_POLICY_DOCUMENT_MISSING: 'VENDOR_POLICY_DOCUMENT_MISSING',
    VENDOR_POLICY_DOCUMENT_TYPE_INVALID: 'VENDOR_POLICY_DOCUMENT_TYPE_INVALID',

    // ── ORDER ─────────────────────────────────────────────────────────────────
    ORDER_CART_EMPTY: 'ORDER_CART_EMPTY',
    ORDER_CART_INVALID: 'ORDER_CART_INVALID',
    ORDER_PRODUCT_NOT_FOUND: 'ORDER_PRODUCT_NOT_FOUND',
    ORDER_VENDOR_NOT_FOUND: 'ORDER_VENDOR_NOT_FOUND',
    ORDER_NO_DELIVERY_AGENCY: 'ORDER_NO_DELIVERY_AGENCY',

    // ── CART ──────────────────────────────────────────────────────────────────
    CART_VARIANT_REQUIRED: 'CART_VARIANT_REQUIRED',
    CART_PRODUCT_NOT_FOUND: 'CART_PRODUCT_NOT_FOUND',
    CART_SERVICE_PRODUCT_NOT_ALLOWED: 'CART_SERVICE_PRODUCT_NOT_ALLOWED',
    CART_VARIANT_NOT_FOUND: 'CART_VARIANT_NOT_FOUND',
    CART_VARIANT_PRODUCT_MISMATCH: 'CART_VARIANT_PRODUCT_MISMATCH',
    CART_DIGITAL_QUANTITY_MUST_BE_ONE: 'CART_DIGITAL_QUANTITY_MUST_BE_ONE',
    CART_MIXED_PRODUCT_TYPES: 'CART_MIXED_PRODUCT_TYPES',
    CART_DIGITAL_LIMIT_REACHED: 'CART_DIGITAL_LIMIT_REACHED',
    CART_NOT_FOUND: 'CART_NOT_FOUND',
    CART_EMPTY_CHECKOUT: 'CART_EMPTY_CHECKOUT',

    // ── BOOKING ───────────────────────────────────────────────────────────────
    BOOKING_PRODUCT_NOT_FOUND: 'BOOKING_PRODUCT_NOT_FOUND',
    BOOKING_USER_NOT_FOUND: 'BOOKING_USER_NOT_FOUND',
    BOOKING_NOT_FOUND: 'BOOKING_NOT_FOUND',
    BOOKING_UNAUTHORIZED: 'BOOKING_UNAUTHORIZED',
    BOOKING_ALREADY_CANCELLED: 'BOOKING_ALREADY_CANCELLED',
    BOOKING_CALENDAR_SYNC_FAILED: 'BOOKING_CALENDAR_SYNC_FAILED',
    BOOKING_INVALID_STATUS_TRANSITION: 'BOOKING_INVALID_STATUS_TRANSITION',
    BOOKING_PAYMENT_NOT_REQUIRED: 'BOOKING_PAYMENT_NOT_REQUIRED',
    BOOKING_ALREADY_PAID: 'BOOKING_ALREADY_PAID',
    BOOKING_INVALID_PAYMENT_METHOD: 'BOOKING_INVALID_PAYMENT_METHOD',
    BOOKING_TERMINAL_STATE: 'BOOKING_TERMINAL_STATE',
    BOOKING_SLOT_NOT_LOCKED: 'BOOKING_SLOT_NOT_LOCKED',
    BOOKING_SLOT_LOCKED: 'BOOKING_SLOT_LOCKED',
    BOOKING_FORBIDDEN: 'BOOKING_FORBIDDEN',
    BOOKING_INVALID_SLOT_ID: 'BOOKING_INVALID_SLOT_ID',
    BOOKING_NOT_RESCHEDULABLE: 'BOOKING_NOT_RESCHEDULABLE',
    BOOKING_SLOT_FULL: 'BOOKING_SLOT_FULL',

    // ── AVAILABILITY RULES (service products) ─────────────────────────────────
    AVAILABILITY_PRODUCT_NOT_FOUND: 'AVAILABILITY_PRODUCT_NOT_FOUND',
    AVAILABILITY_RULE_NOT_FOUND: 'AVAILABILITY_RULE_NOT_FOUND',
    AVAILABILITY_INVALID_PRODUCT_TYPE: 'AVAILABILITY_INVALID_PRODUCT_TYPE',
    AVAILABILITY_INVALID_TIME_RANGE: 'AVAILABILITY_INVALID_TIME_RANGE',
    AVAILABILITY_TIME_OVERLAP: 'AVAILABILITY_TIME_OVERLAP',
    AVAILABILITY_FORBIDDEN: 'AVAILABILITY_FORBIDDEN',

    // ── ADMIN ─────────────────────────────────────────────────────────────────
    ADMIN_NOT_FOUND: 'ADMIN_NOT_FOUND',
    ADMIN_FORBIDDEN: 'ADMIN_FORBIDDEN',

    // ── BILLING (pricing plans & credit wallet) ───────────────────────────────
    BILLING_PLAN_NOT_FOUND: 'BILLING_PLAN_NOT_FOUND',
    BILLING_PLAN_INACTIVE: 'BILLING_PLAN_INACTIVE',
    BILLING_PLAN_ROLE_MISMATCH: 'BILLING_PLAN_ROLE_MISMATCH',
    BILLING_PLAN_CODE_EXISTS: 'BILLING_PLAN_CODE_EXISTS',
    BILLING_PENDING_PLAN_EXISTS: 'BILLING_PENDING_PLAN_EXISTS',
    BILLING_INSUFFICIENT_CREDITS: 'BILLING_INSUFFICIENT_CREDITS',
    BILLING_LIMIT_EXCEEDED: 'BILLING_LIMIT_EXCEEDED',
    BILLING_WALLET_CONFLICT: 'BILLING_WALLET_CONFLICT',
    BILLING_TOPUP_NOT_FOUND: 'BILLING_TOPUP_NOT_FOUND',
    BILLING_TOPUP_PACK_NOT_FOUND: 'BILLING_TOPUP_PACK_NOT_FOUND',
    BILLING_TOPUP_INVALID_STATE: 'BILLING_TOPUP_INVALID_STATE',
    BILLING_PLAN_PURCHASE_NOT_FOUND: 'BILLING_PLAN_PURCHASE_NOT_FOUND',
    BILLING_PLAN_NOT_PURCHASABLE: 'BILLING_PLAN_NOT_PURCHASABLE',
    BILLING_PURCHASE_INVALID_STATE: 'BILLING_PURCHASE_INVALID_STATE',

    // ── EARNINGS (commission, escrow & payout ledger) ─────────────────────────
    EARNINGS_INVALID_SPLIT: 'EARNINGS_INVALID_SPLIT',
    EARNINGS_ALLOCATION_NOT_FOUND: 'EARNINGS_ALLOCATION_NOT_FOUND',
    EARNINGS_ALREADY_COMPLETED: 'EARNINGS_ALREADY_COMPLETED',
    EARNINGS_ORDER_NOT_CONFIRMABLE: 'EARNINGS_ORDER_NOT_CONFIRMABLE',
    EARNINGS_FORBIDDEN: 'EARNINGS_FORBIDDEN',
    EARNINGS_PAYOUT_ALREADY_PENDING: 'EARNINGS_PAYOUT_ALREADY_PENDING',
    EARNINGS_PAYOUT_METHOD_MISSING: 'EARNINGS_PAYOUT_METHOD_MISSING',
    EARNINGS_PAYOUT_NO_AVAILABLE_BALANCE: 'EARNINGS_PAYOUT_NO_AVAILABLE_BALANCE',
    EARNINGS_PAYOUT_BELOW_MINIMUM: 'EARNINGS_PAYOUT_BELOW_MINIMUM',
    EARNINGS_PAYOUT_REQUEST_NOT_FOUND: 'EARNINGS_PAYOUT_REQUEST_NOT_FOUND',
    EARNINGS_PAYOUT_REQUEST_NOT_PENDING: 'EARNINGS_PAYOUT_REQUEST_NOT_PENDING',

    // ── COD (cash on delivery: collection, cash liabilities, reconciliation) ──
    COD_NOT_AVAILABLE_FOR_DIGITAL: 'COD_NOT_AVAILABLE_FOR_DIGITAL',
    COD_AGENCY_NOT_SUPPORTED: 'COD_AGENCY_NOT_SUPPORTED',
    COD_ORDER_AMOUNT_EXCEEDS_LIMIT: 'COD_ORDER_AMOUNT_EXCEEDS_LIMIT',
    COD_COLLECTION_NOT_FOUND: 'COD_COLLECTION_NOT_FOUND',
    COD_COLLECTION_ALREADY_COLLECTED: 'COD_COLLECTION_ALREADY_COLLECTED',
    COD_COLLECTION_NOT_COLLECTIBLE: 'COD_COLLECTION_NOT_COLLECTIBLE',
    COD_INVALID_CODE: 'COD_INVALID_CODE',
    COD_CODE_ATTEMPTS_EXCEEDED: 'COD_CODE_ATTEMPTS_EXCEEDED',
    COD_CODE_RESEND_TOO_SOON: 'COD_CODE_RESEND_TOO_SOON',
    COD_AGENT_NOT_ASSIGNED: 'COD_AGENT_NOT_ASSIGNED',
    COD_AGENT_EXPOSURE_EXCEEDED: 'COD_AGENT_EXPOSURE_EXCEEDED',
    COD_AGENT_TRUST_TOO_LOW: 'COD_AGENT_TRUST_TOO_LOW',
    COD_AGENT_HAS_OUTSTANDING_CASH: 'COD_AGENT_HAS_OUTSTANDING_CASH',
    COD_DEPOSIT_INVALID_AMOUNT: 'COD_DEPOSIT_INVALID_AMOUNT',
    COD_DEPOSIT_EXCEEDS_BALANCE: 'COD_DEPOSIT_EXCEEDS_BALANCE',
    COD_DEPOSIT_NOT_FOUND: 'COD_DEPOSIT_NOT_FOUND',
    COD_DEPOSIT_ALREADY_RESOLVED: 'COD_DEPOSIT_ALREADY_RESOLVED',
    COD_DEPOSIT_REFERENCE_REQUIRED: 'COD_DEPOSIT_REFERENCE_REQUIRED',
    /** Direct-to-platform deposit for cash the agency has already remitted. */
    COD_DEPOSIT_AGENCY_ALREADY_SETTLED: 'COD_DEPOSIT_AGENCY_ALREADY_SETTLED',
    COD_DEPOSIT_WRONG_RECIPIENT: 'COD_DEPOSIT_WRONG_RECIPIENT',
    COD_REMITTANCE_INVALID_AMOUNT: 'COD_REMITTANCE_INVALID_AMOUNT',
    COD_REMITTANCE_EXCEEDS_LIABILITY: 'COD_REMITTANCE_EXCEEDS_LIABILITY',
    COD_REMITTANCE_NOT_FOUND: 'COD_REMITTANCE_NOT_FOUND',
    COD_REMITTANCE_ALREADY_RESOLVED: 'COD_REMITTANCE_ALREADY_RESOLVED',
    COD_DISCREPANCY_NOT_FOUND: 'COD_DISCREPANCY_NOT_FOUND',
    COD_DISCREPANCY_ALREADY_RESOLVED: 'COD_DISCREPANCY_ALREADY_RESOLVED',

    // ── AUTH EXTENDED ─────────────────────────────────────────────────────────
    AUTH_OAUTH_STATE_INVALID: 'AUTH_OAUTH_STATE_INVALID',
    AUTH_OAUTH_STATE_EXPIRED: 'AUTH_OAUTH_STATE_EXPIRED',

    // ── STORAGE ───────────────────────────────────────────────────────────────
    STORAGE_FILE_NOT_FOUND: 'STORAGE_FILE_NOT_FOUND',
    STORAGE_DELETE_FAILED: 'STORAGE_DELETE_FAILED',
    STORAGE_QUOTA_EXCEEDED: 'STORAGE_QUOTA_EXCEEDED',
    STORAGE_CLEANUP_FAILED: 'STORAGE_CLEANUP_FAILED',

    // ── CATALOG EXTENDED ──────────────────────────────────────────────────────
    CATALOG_DIGITAL_ASSET_ACCESS_DENIED: 'CATALOG_DIGITAL_ASSET_ACCESS_DENIED',
    CATALOG_SHIPPING_NOT_FOUND: 'CATALOG_SHIPPING_NOT_FOUND',
    CATALOG_SHIPPING_ACCESS_DENIED: 'CATALOG_SHIPPING_ACCESS_DENIED',

    // ── COMMAND BUS ───────────────────────────────────────────────────────────
    COMMAND_ALREADY_REGISTERED: 'COMMAND_ALREADY_REGISTERED',
    COMMAND_NOT_FOUND: 'COMMAND_NOT_FOUND',

    // ── WHATSAPP EXTENDED ─────────────────────────────────────────────────────
    WHATSAPP_LINK_FAILED: 'WHATSAPP_LINK_FAILED',
    WHATSAPP_INVALID_PAYLOAD: 'WHATSAPP_INVALID_PAYLOAD',
    WHATSAPP_POLICY_VIOLATION: 'WHATSAPP_POLICY_VIOLATION',
    WHATSAPP_PROVIDER_REJECTED: 'WHATSAPP_PROVIDER_REJECTED',
    WHATSAPP_VALIDATION_ERROR: 'WHATSAPP_VALIDATION_ERROR',
    WHATSAPP_IDEMPOTENCY_REQUIRED: 'WHATSAPP_IDEMPOTENCY_REQUIRED',
    WHATSAPP_DUPLICATE_MESSAGE: 'WHATSAPP_DUPLICATE_MESSAGE',
    WHATSAPP_UNSUPPORTED_MESSAGE_TYPE: 'WHATSAPP_UNSUPPORTED_MESSAGE_TYPE',

    // ── DIGITAL ASSET ─────────────────────────────────────────────────────────
    DIGITAL_ASSET_NOT_FOUND: 'DIGITAL_ASSET_NOT_FOUND',
    DIGITAL_ASSET_ACCESS_DENIED: 'DIGITAL_ASSET_ACCESS_DENIED',
    DIGITAL_ASSET_IN_USE: 'DIGITAL_ASSET_IN_USE',

    // ── DIGITAL ENTITLEMENT ───────────────────────────────────────────────────
    DIGITAL_ENTITLEMENT_CONFIG_MISSING: 'DIGITAL_ENTITLEMENT_CONFIG_MISSING',
    DIGITAL_ENTITLEMENT_CONFIG_INACTIVE: 'DIGITAL_ENTITLEMENT_CONFIG_INACTIVE',

    // ── MIDDLEWARE / ROUTER FALLBACKS — DO NOT USE IN SERVICES ───────────────
    INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',  // assigned by global handler
    NOT_FOUND: 'NOT_FOUND',              // unmatched routes only
    VALIDATION_ERROR: 'VALIDATION_ERROR',       // ZodError catch in handler only
} as const);

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
